---
- name: Set MySQL root password
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password"
    value: "{{ mysql_root_password }}"
    vtype: "password"
  no_log: true
    
    
- name: Confirm MySQL root password
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password_again"
    value: "{{ mysql_root_password }}"
    vtype: "password"
  no_log: true
  

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Make sure that MySQL is enabled
  service:
    name: mysql
    state: started
    enabled: yes

- block:
    - name: Secure MySQL with shell commands (EOF)
      shell: |
        mysql -u root -p"{{ mysql_root_password }}" <<EOF
        DELETE FROM mysql.user WHERE User='';
        DROP DATABASE IF EXISTS test;
        DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash
      no_log: true
 
  rescue:
    - name: Handling MySQL Secure Installation Error
      debug:
        msg: "Failed to secure MySQL. Check the root password."
        
  always:
    - name: Always notify completion
      debug:
        msg: "MySQL setup attempted."
