version: '3.8'

services:
  web:
    container_name: fastapi-app-testing1
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      - redis    
        
  postgres:
    container_name: postgre-container-testing1
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:8.0.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  nginx:
    container_name: nginx-proxy-testing1
    image: nginx:1.27.5-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: